### Задание 1

In [2]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [6]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [10]:
np.reshape(a,(2,6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
np.reshape(a,(3,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
np.reshape(a,(4,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
np.reshape(a,(6,2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [17]:
np.reshape(a,(12,1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [20]:
np.reshape(a,(2,-1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [22]:
np.reshape(a,(3,-1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
np.reshape(a,(4,-1))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [24]:
np.reshape(a,(-1,2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [25]:
np.reshape(a,(-1,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным

Нет, он всё равно является двухмерным

In [37]:
np.reshape(a,(12,1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [71]:
b = np.random.randn(3,4)
print(b)
print(b.size)
c = b.flatten()
print(c)
print(c.size)

[[ 0.48231202  1.7472114  -1.37959835  1.38797259]
 [-0.00493435  1.86886569 -0.360603   -1.23830816]
 [ 1.63858604  1.20628748  0.79040424 -0.49150466]]
12
[ 0.48231202  1.7472114  -1.37959835  1.38797259 -0.00493435  1.86886569
 -0.360603   -1.23830816  1.63858604  1.20628748  0.79040424 -0.49150466]
12


6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?

In [66]:
a = np.arange(20,0,-2)
print(a)
b = np.array([np.arange(20,1,-2)])
print(b)

[20 18 16 14 12 10  8  6  4  2]
[[20 18 16 14 12 10  8  6  4  2]]


Разница в том , что массив a является одномерным, а b многомерным. Доступ к элементам разный

In [70]:
print(a[0])
print(b[0,0])

20
20


7. Вертикально соединить массивы a и b. a - двумерный массив из нулей,
число строк которого больше 1 и на 1 меньше, чем число строк двумерного
массива b, состоящего из единиц.

In [86]:
a = np.zeros((2,2))
b = np.ones((3,2))
print(f"Матрица a:\n{a}")
print(f"Матрица b:\n{b}")
v = np.vstack((a,b))
print(f"Результат вертикального соединия массивов a и b:\n{v}")
print(f"Size v = {v.size}")

Матрица a:
[[0. 0.]
 [0. 0.]]
Матрица b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Результат вертикального соединия массивов a и b:
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Size v = 10


8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из
4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?

In [102]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
A = np.reshape(a,(4,3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [93]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [94]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [95]:
B.shape

(4, 4)

In [99]:
np.linalg.det(B)

0.0

#Binv = np.linalg.inv(B)
Обратную матрицу не получить, т.к. определитель матрицы равен 0 (матрица является вырожденной).

9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно.
Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [101]:
np.random.seed(42)

In [114]:
c = np.random.randint(0,16,16)
c

array([ 3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3])

In [115]:
C = np.reshape(c,(4,-1))
C

array([[ 3, 12, 14, 10],
       [ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3]])

In [116]:
D = B + C * 10
D

array([[ 35, 134, 163, 132],
       [ 84, 170, 126, 182],
       [113, 106, 209, 312],
       [132, 192, 252, 332]])

In [117]:
np.linalg.det(D)

21320000.000000034

In [118]:
np.linalg.matrix_rank(D)

4

In [134]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.0421257 , -0.04781989, -0.07423077,  0.11272233],
       [ 0.00713133,  0.01837899,  0.00807692, -0.02050094],
       [-0.00235084, -0.03018386, -0.02807692,  0.04386679],
       [ 0.01440901,  0.03129456,  0.04615385, -0.06324578]])

10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы.
С помощью функции numpy.where, используя матрицу D_inv в качестве маски,
а матрицы B и C - в качестве источников данных,
получите матрицу E размером 4x4.
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1,
должны быть равны соответствующему элементу матрицы B,
а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0,
должны быть равны соответствующему элементу матрицы C.

In [135]:
D_inv[D_inv<0] = 0
D_inv[D_inv>0] = 1
D_inv

array([[0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 1., 0.]])

In [137]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [138]:
C

array([[ 3, 12, 14, 10],
       [ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3]])

In [136]:
E = np.where(D_inv, B, C)
E

array([[  3,  12,  14,  32],
       [ 14,  50,  86,   6],
       [  9,   2,   6, 212],
       [ 32, 122, 212,   3]])

### Задание 2

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [20]:
a = np.array([[ 1,  6],
              [ 2,  8],
              [ 3, 11],
              [ 3, 10],
              [ 1,  7]])
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 3

Вычислите массив a_centered, отняв от значений массива а
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 4

Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp.
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [17]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
a_centered_sp

8.0

In [19]:
a_centered_sp / (a_centered.shape[0] -1)


2.0

### Задание 5

Число, которое мы получили в конце задания 3 является
ковариацией двух признаков, содержащихся в массиве а.
В задании 4 мы делили сумму произведений центрированных
признаков на N-1, а не на N, поэтому полученная нами величина
является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Ссылка
В этом задании проверьте получившееся число, вычислив
ковариацию еще одним способом - с помощью функции np.cov.
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [23]:
np.cov(a.T)[0,1]

2.0